"""Provenance and audit: where every memory came from, including across agents.

The record follows the W3C PROV data model (https://www.w3.org/TR/prov-dm/):
- a memory write is an Entity;
- a recall is an Activity that *used* the memories it returned;
- a turn (something an agent said) is an Activity *informed by* the recalls it drew on;
- a memory *was generated by* the turns it was formed from, or *was derived from* other memories;
- agents are *associated with* activities and memories are *attributed to* their authors.

That makes a memory's origin recoverable across agents: when A retells an {A,B} conversation to C,
the memory C forms points back to what A recalled. `export_prov` writes the record as PROV-JSON.

Storage is SQLite, one file per partition. Links are rows in indexed edge tables, so a trail in
either direction is one recursive query. The log is itself memory, so it is partitioned like memory:
each high-assurance location keeps its own file and nothing recorded there (not even that a recall
happened) reaches the shared file. Queries from inside a high-assurance location attach the shared
file too (personal memory from outside may be recalled there); nothing ever reads a high-assurance
file from outside it.

Trails are shown to an asker through the same rules as recall:
- a source they can read is shown in full;
- a source they can't read shows only that it exists and where it came from, and nothing of what
  it was built from (docs/vault/Concepts/Label and Memory Types.md);
- a high-assurance source they can't read is left out entirely.
"""

from __future__ import annotations

import json
import sqlite3
from contextlib import contextmanager
import threading
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from memgate.policy import Policy
from memgate.world import World

SHARED = "shared"

SCHEMA = """
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;   -- with WAL: durable across application crashes, fast commits
CREATE TABLE IF NOT EXISTS entity (          -- prov:Entity: a stored memory
  id TEXT PRIMARY KEY, ts REAL NOT NULL, kind TEXT NOT NULL, author TEXT, location TEXT,
  label_set TEXT NOT NULL, text TEXT);
CREATE TABLE IF NOT EXISTS activity (        -- prov:Activity: a recall or a turn
  id TEXT PRIMARY KEY, ts REAL NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('recall', 'turn')),
  agent TEXT NOT NULL, location TEXT, text TEXT, allowed TEXT);
CREATE TABLE IF NOT EXISTS associated_with (activity_id TEXT NOT NULL, agent TEXT NOT NULL, PRIMARY KEY (activity_id, agent));
CREATE TABLE IF NOT EXISTS used (activity_id TEXT NOT NULL, entity_id TEXT NOT NULL, rank INTEGER, PRIMARY KEY (activity_id, entity_id));
CREATE TABLE IF NOT EXISTS informed_by (activity_id TEXT NOT NULL, informant_id TEXT NOT NULL, PRIMARY KEY (activity_id, informant_id));
CREATE TABLE IF NOT EXISTS generated_by (entity_id TEXT NOT NULL, activity_id TEXT NOT NULL, PRIMARY KEY (entity_id, activity_id));
CREATE TABLE IF NOT EXISTS derived_from (entity_id TEXT NOT NULL, source_id TEXT NOT NULL, PRIMARY KEY (entity_id, source_id));
CREATE TABLE IF NOT EXISTS audit (ts REAL NOT NULL, event TEXT NOT NULL, detail TEXT);
-- Materialised at write time: a memory's direct sources (see SOURCE_EDGE), indexed both ways, so
-- lineage walks are index lookups rather than three-table joins.
CREATE TABLE IF NOT EXISTS lineage (entity_id TEXT NOT NULL, source_id TEXT NOT NULL, PRIMARY KEY (entity_id, source_id));
CREATE INDEX IF NOT EXISTS lineage_source ON lineage (source_id);
CREATE INDEX IF NOT EXISTS entity_label_set ON entity (label_set);
CREATE INDEX IF NOT EXISTS activity_agent ON activity (agent, kind);
CREATE INDEX IF NOT EXISTS associated_agent ON associated_with (agent);
CREATE INDEX IF NOT EXISTS used_entity ON used (entity_id);
CREATE INDEX IF NOT EXISTS informed_informant ON informed_by (informant_id);
CREATE INDEX IF NOT EXISTS generated_activity ON generated_by (activity_id);
CREATE INDEX IF NOT EXISTS derived_source ON derived_from (source_id);
"""

EDGE_TABLES = ("entity", "activity", "associated_with", "used", "informed_by", "generated_by", "derived_from", "lineage")
BATCH = 500  # SQLite host-parameter limit headroom for IN (...) lists

# A memory's direct sources: memories it was derived from, plus the memories returned by the recalls
# that informed the turns it was generated by. Kept as a definition (and a check) of `lineage`.
SOURCE_EDGE = """
SELECT entity_id, source_id FROM derived_from
UNION
SELECT g.entity_id, u.entity_id FROM generated_by g
  JOIN informed_by i ON i.activity_id = g.activity_id
  JOIN used u ON u.activity_id = i.informant_id
"""


def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:16]}"


@dataclass
class TrailNode:
    """One memory in a provenance trail, as the asker is allowed to see it."""
    write_id: str
    visibility: str                 # "full" or "existence"
    location: str | None = None
    kind: str | None = None
    text: str | None = None
    author: str | None = None
    sources: list["TrailNode"] = field(default_factory=list)


class ProvenanceLog:
    def __init__(self, root: str | Path, world):
        """`world` is a World, or anything with a `world` attribute (a Gate), so reloads are followed."""
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)
        self._world = world
        self._conns: dict[str, sqlite3.Connection] = {}
        self._lock = threading.RLock()

    @property
    def world(self) -> World:
        return self._world if isinstance(self._world, World) else self._world.world

    # -- partitions --------------------------------------------------------------------------------
    def partition(self, location: str | None) -> str:
        """High-assurance locations keep their own log; everything else shares one."""
        if location and location in self.world.locations and self.world.high_assurance(location):
            return f"ha-{location}"
        return SHARED

    def _path(self, partition: str) -> Path:
        return self.root / f"provenance-{partition}.sqlite"

    def _write_conn(self, partition: str) -> sqlite3.Connection:
        if partition not in self._conns:
            db = sqlite3.connect(str(self._path(partition)), check_same_thread=False, timeout=30)
            db.executescript(SCHEMA)
            self._conns[partition] = db
        return self._conns[partition]

    @contextmanager
    def _read_conn(self, partitions: list[str]):
        """A read-only connection whose temp views span `partitions` (the asker's own partition, then shared)."""
        db = sqlite3.connect("file:memgate-read?mode=memory", uri=True, check_same_thread=False)
        try:
            db.row_factory = sqlite3.Row
            names = []
            for i, p in enumerate(partitions):
                if not self._path(p).exists():
                    continue
                name = f"p{i}"
                db.execute(f"ATTACH DATABASE ? AS {name}", (f"file:{self._path(p)}?mode=ro",))
                names.append(name)
            self._define_views(db, names)
            yield db
        finally:
            db.close()

    def _define_views(self, db: sqlite3.Connection, names: list[str]) -> None:
        for table in EDGE_TABLES:
            if names:
                db.execute(f"CREATE TEMP VIEW {table} AS " + " UNION ALL ".join(f"SELECT * FROM {n}.{table}" for n in names))
            else:
                self._empty_view(db, table)
        db.execute(f"CREATE TEMP VIEW source_edge AS {SOURCE_EDGE}")

    @staticmethod
    def _empty_view(db: sqlite3.Connection, table: str) -> None:
        cols = {"entity": "id, ts, kind, author, location, label_set, text", "activity": "id, ts, kind, agent, location, text, allowed",
                "associated_with": "activity_id, agent", "used": "activity_id, entity_id, rank",
                "informed_by": "activity_id, informant_id", "generated_by": "entity_id, activity_id",
                "derived_from": "entity_id, source_id", "lineage": "entity_id, source_id"}[table]
        db.execute(f"CREATE TEMP VIEW {table} AS SELECT " + ", ".join(f"NULL AS {c.strip()}" for c in cols.split(",")) + " WHERE 0")

    def _partitions_visible_from(self, location: str | None) -> list[str]:
        """The shared log, plus the asker's own high-assurance partition if they are inside one."""
        own = self.partition(location)
        return [SHARED] if own == SHARED else [own, SHARED]

    def _write(self, location: str | None, statements: list[tuple[str, tuple]]) -> None:
        with self._lock:
            db = self._write_conn(self.partition(location))
            with db:
                for sql, row in statements:
                    db.execute(sql, row)

    # -- recording ---------------------------------------------------------------------------------
    def record_recall(self, agent: str, location: str, query: str, allowed: set[str],
                      returned: list[tuple[str, str]]) -> str:
        """`returned` is [(write_id, label_set_id)] for each memory the recall gave back, in rank order."""
        rid = new_id("rc")
        stmts = [("INSERT INTO activity VALUES (?,?,?,?,?,?,?)",
                  (rid, time.time(), "recall", agent, location, query, json.dumps(sorted(allowed)))),
                 ("INSERT INTO associated_with VALUES (?,?)", (rid, agent))]
        stmts += [("INSERT OR IGNORE INTO used VALUES (?,?,?)", (rid, wid, rank)) for rank, (wid, _) in enumerate(returned)]
        self._write(location, stmts)
        return rid

    def record_turn(self, speaker: str, location: str, participants: list[str], text: str, recalls: list[str]) -> str:
        tid = new_id("tn")
        stmts = [("INSERT INTO activity VALUES (?,?,?,?,?,?,?)", (tid, time.time(), "turn", speaker, location, text, None))]
        stmts += [("INSERT OR IGNORE INTO associated_with VALUES (?,?)", (tid, p)) for p in sorted(set(participants) | {speaker})]
        stmts += [("INSERT OR IGNORE INTO informed_by VALUES (?,?)", (tid, r)) for r in recalls]
        self._write(location, stmts)
        return tid

    def record_write(self, write_id: str, author: str, location: str, label_set: str, kind: str, text: str, *,
                     turns: list[str] = (), derived_from: list[str] = ()) -> None:
        stmts = [("INSERT INTO entity VALUES (?,?,?,?,?,?,?)", (write_id, time.time(), kind, author, location, label_set, text))]
        stmts += [("INSERT OR IGNORE INTO generated_by VALUES (?,?)", (write_id, t)) for t in turns]
        stmts += [("INSERT OR IGNORE INTO derived_from VALUES (?,?)", (write_id, s)) for s in derived_from]
        stmts += [("INSERT OR IGNORE INTO lineage VALUES (?,?)", (write_id, s)) for s in derived_from]
        # Turns and their recalls happen where the memory is written, so they are in this partition.
        stmts += [("""INSERT OR IGNORE INTO lineage SELECT ?, u.entity_id FROM informed_by i
                      JOIN used u ON u.activity_id = i.informant_id WHERE i.activity_id = ?""", (write_id, t)) for t in turns]
        self._write(location, stmts)

    def audit(self, location: str | None, event: str, **detail) -> None:
        self._write(location, [("INSERT INTO audit VALUES (?,?,?)", (time.time(), event, json.dumps(detail, default=str)))])

    # -- lineage queries ---------------------------------------------------------------------------
    @staticmethod
    def _step(db: sqlite3.Connection, frontier: list[str], up: bool) -> list[tuple[str, str]]:
        """One level of lineage for a whole frontier: (node, neighbour) pairs."""
        col, other = ("entity_id", "source_id") if up else ("source_id", "entity_id")
        out = []
        for k in range(0, len(frontier), BATCH):
            chunk = frontier[k:k + BATCH]
            q = ",".join("?" * len(chunk))
            out += db.execute(f"SELECT {col}, {other} FROM lineage WHERE {col} IN ({q})", chunk).fetchall()
        return [(a, b) for a, b in out]

    def _walk(self, start: list[str], partitions: list[str], depth: int, up: bool) -> list[tuple[str, str, int]]:
        """Breadth-first walk visiting each memory once: (neighbour, reached-from, depth) per new memory."""
        seen, frontier, out = set(start), list(dict.fromkeys(start)), []
        with self._read_conn(partitions) as db:
            for d in range(1, depth + 1):
                nxt = []
                for node, nb in self._step(db, frontier, up):
                    if nb not in seen:
                        seen.add(nb)
                        nxt.append(nb)
                        out.append((nb, node, d))
                if not nxt:
                    break
                frontier = nxt
        return out

    def sources_of(self, write_id: str, partitions: list[str]) -> list[str]:
        """Direct sources of a memory (one step back)."""
        with self._read_conn(partitions) as db:
            return [nb for _, nb in self._step(db, [write_id], up=True)]

    def ancestors(self, write_id: str, partitions: list[str], depth: int = 10) -> list[tuple[str, str, int]]:
        """Every memory upstream of `write_id`, each once: (source, memory it was first reached from, depth)."""
        return self._walk([write_id], partitions, depth, up=True)

    def descendants(self, write_id: str, partitions: list[str] | None = None, depth: int = 10) -> list[tuple[str, int]]:
        """Impact: every memory built, directly or through retelling, from `write_id` (for retraction)."""
        return sorted(((nb, d) for nb, _, d in self._walk([write_id], partitions or [SHARED], depth, up=False)),
                      key=lambda x: (x[1], x[0]))

    def exposure(self, agent: str, partitions: list[str] | None = None) -> dict[str, int]:
        """What an agent has been shown: recalled memories per label set."""
        with self._read_conn(partitions or [SHARED]) as db:
            rows = db.execute("""
                SELECT e.label_set, COUNT(DISTINCT e.id) FROM activity a JOIN used u ON u.activity_id = a.id
                JOIN entity e ON e.id = u.entity_id WHERE a.kind = 'recall' AND a.agent = ?
                GROUP BY e.label_set""", (agent,)).fetchall()
        return {r[0]: r[1] for r in rows}

    def flows(self, label_set: str, partitions: list[str] | None = None, depth: int = 10) -> dict[str, list]:
        """Where memories of one label set went: who recalled them, and memories in other label sets
        built from them (retellings, carry-outs). The leak audit for the selective-memory benchmark."""
        partitions = partitions or [SHARED]
        with self._read_conn(partitions) as db:
            recalled_by = db.execute("""
                SELECT a.agent, a.location, COUNT(*) FROM entity e JOIN used u ON u.entity_id = e.id
                JOIN activity a ON a.id = u.activity_id WHERE e.label_set = ? AND a.kind = 'recall'
                GROUP BY a.agent, a.location ORDER BY 1, 2""", (label_set,)).fetchall()
            members = [r[0] for r in db.execute("SELECT id FROM entity WHERE label_set = ?", (label_set,))]
        reached = self._walk(members, partitions, depth, up=False)
        info: dict[str, sqlite3.Row] = {}
        with self._read_conn(partitions) as db:
            ids = [nb for nb, _, _ in reached]
            for k in range(0, len(ids), BATCH):
                chunk = ids[k:k + BATCH]
                q = ",".join("?" * len(chunk))
                info.update({r["id"]: r for r in db.execute(f"SELECT * FROM entity WHERE id IN ({q})", chunk)})
        derived = sorted(((nb, info[nb]["label_set"], info[nb]["kind"], info[nb]["location"], d)
                          for nb, _, d in reached if nb in info and info[nb]["label_set"] != label_set),
                         key=lambda r: (r[4], r[0]))
        return {"recalled_by": [tuple(r) for r in recalled_by], "derived_elsewhere": derived}

    # -- trails for an asker -----------------------------------------------------------------------
    def trail(self, write_id: str, asker: str, location: str, policy: Policy, depth: int = 3) -> TrailNode | None:
        """The provenance trail of a memory as `asker` at `location` may see it (None if sealed)."""
        allowed = policy.allowed_ids(asker, location)
        partitions = self._partitions_visible_from(location)
        edges = self.ancestors(write_id, partitions, depth)
        ids = [write_id] + [a for a, _, _ in edges]
        rows: dict[str, sqlite3.Row] = {}
        with self._read_conn(partitions) as db:
            for k in range(0, len(ids), BATCH):
                chunk = ids[k:k + BATCH]
                q = ",".join("?" * len(chunk))
                rows.update({r["id"]: r for r in db.execute(f"SELECT * FROM entity WHERE id IN ({q})", chunk)})
        children: dict[str, list[str]] = {}
        for src, child, _ in edges:
            children.setdefault(child, []).append(src)

        def node(wid: str, d: int, seen: frozenset[str]) -> TrailNode | None:
            w = rows.get(wid)
            if w is None:
                return None  # unknown, or recorded in a high-assurance partition the asker is outside
            if w["label_set"] in allowed:
                n = TrailNode(wid, "full", w["location"], w["kind"], w["text"], w["author"])
            elif self.partition(w["location"]) != SHARED:
                return None  # a sealed high-assurance source: not even its existence is shown
            else:
                n = TrailNode(wid, "existence", w["location"])
            if n.visibility == "full" and d > 0 and wid not in seen:
                for src in dict.fromkeys(children.get(wid, [])):
                    child = node(src, d - 1, seen | {wid})
                    if child:
                        n.sources.append(child)
            return n

        return node(write_id, depth, frozenset())

    # -- PROV-JSON export --------------------------------------------------------------------------
    def export_prov(self, partitions: list[str] | None = None, include_text: bool = False) -> dict:
        """The record as W3C PROV-JSON (https://www.w3.org/submissions/prov-json/). Memory text is left
        out unless asked for, so an export can be shared without the memories themselves."""
        with self._read_conn(partitions or [SHARED]) as db:
            doc: dict = {"prefix": {"mg": "urn:memgate:"}, "entity": {}, "activity": {}, "agent": {},
                         "used": {}, "wasInformedBy": {}, "wasGeneratedBy": {}, "wasDerivedFrom": {},
                         "wasAssociatedWith": {}, "wasAttributedTo": {}}
            agents: set[str] = set()
            for e in db.execute("SELECT * FROM entity"):
                attrs = {"prov:type": "mg:Memory", "mg:kind": e["kind"], "mg:labelSet": e["label_set"],
                         "mg:location": e["location"], "mg:time": e["ts"]}
                if include_text:
                    attrs["prov:value"] = e["text"]
                doc["entity"][f"mg:{e['id']}"] = attrs
                if e["author"]:
                    agents.add(e["author"])
                    doc["wasAttributedTo"][f"_:attr-{e['id']}"] = {"prov:entity": f"mg:{e['id']}", "prov:agent": f"mg:agent-{e['author']}"}
            for a in db.execute("SELECT * FROM activity"):
                attrs = {"prov:type": f"mg:{a['kind'].capitalize()}", "mg:location": a["location"], "prov:startTime": a["ts"]}
                if include_text and a["text"]:
                    attrs["mg:text"] = a["text"]
                doc["activity"][f"mg:{a['id']}"] = attrs
            for i, r in enumerate(db.execute("SELECT * FROM associated_with")):
                agents.add(r["agent"])
                doc["wasAssociatedWith"][f"_:assoc{i}"] = {"prov:activity": f"mg:{r['activity_id']}", "prov:agent": f"mg:agent-{r['agent']}"}
            for i, r in enumerate(db.execute("SELECT * FROM used")):
                doc["used"][f"_:used{i}"] = {"prov:activity": f"mg:{r['activity_id']}", "prov:entity": f"mg:{r['entity_id']}"}
            for i, r in enumerate(db.execute("SELECT * FROM informed_by")):
                doc["wasInformedBy"][f"_:inf{i}"] = {"prov:informed": f"mg:{r['activity_id']}", "prov:informant": f"mg:{r['informant_id']}"}
            for i, r in enumerate(db.execute("SELECT * FROM generated_by")):
                doc["wasGeneratedBy"][f"_:gen{i}"] = {"prov:entity": f"mg:{r['entity_id']}", "prov:activity": f"mg:{r['activity_id']}"}
            for i, r in enumerate(db.execute("SELECT * FROM derived_from")):
                doc["wasDerivedFrom"][f"_:der{i}"] = {"prov:generatedEntity": f"mg:{r['entity_id']}", "prov:usedEntity": f"mg:{r['source_id']}"}
            doc["agent"] = {f"mg:agent-{a}": {"prov:type": "prov:SoftwareAgent"} for a in sorted(agents)}
        return {k: v for k, v in doc.items() if v}
